server:
  port: 8080

spring:
  application:
    name: claim-service
  sleuth:
    sampler:
      probability: 1.0
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongo
      repositories:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9091/eureka
